import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`antialiased ${geistSans.variable} ${geistMono.variable} ${rubik.className}`}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
